### ISSUE TITLE
TODO: fixes FRONTEND

### ISSUE THREAD

**Issue by idanizi** [idanbaal/dogkeeping#3]
# TODO:

- [ ] Home link at the `navbar` renders the hole screen - *todo*: render only the content section of the screen
- [ ] `sidebar` - make it wider / expand.
![image](https://user-images.githubusercontent.com/9889268/50444585-fc177300-0911-11e9-8e5d-5507e61f0fb2.png)

- [ ] About link at `navbar` - make it's style as "Home" link
![image](https://user-images.githubusercontent.com/9889268/50444582-eefa8400-0911-11e9-8fa7-4251615b8d52.png)

- [ ] routing - make it workwith `breadcrums`
- [ ] fix "CoreUI for React' window title and logo (gifycon)
![image](https://user-images.githubusercontent.com/9889268/50444574-da1df080-0911-11e9-8329-970798797b71.png)

- [ ] fix "about/about" route
![image](https://user-images.githubusercontent.com/9889268/50444562-c6728a00-0911-11e9-9623-fa3c33d8e485.png)

# Done:
